spring.application.name=load-optimizer
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
spring.servlet.multipart.max-request-size=1MB
spring.servlet.multipart.max-file-size=1MB
server.tomcat.max-http-form-post-size=1MB
